name: AfaEssentials
version: '2.0-SNAPSHOT'
main: com.afa.testPlugin.Main
api-version: '1.21'
authors: [ AfaGaming ]
description: A cool test plugin.
commands:
  heal:
  feed:
  fly:
  gmc:
  gms:
  gma:
  gmsp:
  gamemode:
  god:
  opme:
  setspawn:
  spawn:
#  config:
#    description: enable or disable commands.
#    usage: /config <command> [<true/false>]
